name: assignment4_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - GitPython==3.1.45
    - PyYAML==6.0.3
    - accelerate==0.21.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - certifi==2025.10.5
    - charset-normalizer==3.4.4
    - click==8.3.0
    - contourpy==1.3.2
    - cycler==0.12.1
    - datasets==2.13.1
    - dill==0.3.6
    - filelock==3.20.0
    - fonttools==4.60.1
    - frozenlist==1.8.0
    - fsspec==2023.9.2
    - gitdb==4.0.12
    - hf-xet==1.2.0
    - huggingface-hub==0.36.0
    - idna==3.11
    - joblib==1.5.2
    - kiwisolver==1.4.9
    - matplotlib==3.10.7
    - multidict==6.7.0
    - multiprocess==0.70.14
    - numpy==1.24.4
    - packaging==25.0
    - pandas==1.5.3
    - pillow==12.0.0
    - platformdirs==4.5.0
    - portalocker==3.2.0
    - propcache==0.4.1
    - protobuf==6.33.0
    - psutil==7.1.3
    - pyarrow==12.0.0
    - pyarrow-hotfix==0.7
    - pydantic==2.12.4
    - pydantic_core==2.41.5
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - regex==2025.11.3
    - requests==2.32.5
    - safetensors==0.6.2
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - sentry-sdk==2.43.0
    - six==1.17.0
    - smmap==5.0.2
    - threadpoolctl==3.6.0
    - tokenizers==0.13.3
    - torch==1.13.1+cu117
    - torchaudio==0.13.1+cu117
    - torchdata==0.5.1
    - torchtext==0.14.1
    - torchvision==0.14.1+cu117
    - tqdm==4.67.1
    - transformers==4.30.2
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - urllib3==2.5.0
    - wandb==0.22.3
    - xxhash==3.6.0
    - yarl==1.22.0

prefix: "/home/cs529322/miniforge3/envs/assignment4_env"
